### ISSUE TITLE
Latex format requirements

### ISSUE THREAD

**Issue by elikrause** [DarkEnergyScienceCollaboration/SRM-Table#1]
Hi,
does someone understand the formatting requirements for this script beyond the basic SRM formatting? 
The tjp.tex SRM file produces a valid pdf, but when I feed this file to extract_deliverables.py, the script only indentifies three out of the many many tasks. 
Thanks,
Elisabeth

**Comment by joezuntz** [comment]
Hi Elisabeth,

It's supposed to look for anything matching `\keytask[A]{B}{C}` where A B and C are anything.  It looks like many of the TJP key tasks don't have the square bracket bit, which defines a code name for the task. You can fix this by doing a find-replace of `\keytask{` with `\keytask[TMP]{`

**Comment by elikrause** [comment]
Thank you @joezuntz , that fixed most my problems.
